# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JsonPerf' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JsonPerf
  #pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'swift3'
pod 'Freddy'

  target 'JsonPerfTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
